//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEStudyTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DCE A3 Standard")]
        public string TYPE_NAME_TITLEBLOCK {
            get {
                return ((string)(this["TYPE_NAME_TITLEBLOCK"]));
            }
            set {
                this["TYPE_NAME_TITLEBLOCK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Légendes")]
        public string LEGEND_NAME_STANDARD {
            get {
                return ((string)(this["LEGEND_NAME_STANDARD"]));
            }
            set {
                this["LEGEND_NAME_STANDARD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Charge Verticale par Pieux en Tonnes à ELS(G+Q) Test")]
        public string FOUNDATION_TITLE_PILE {
            get {
                return ((string)(this["FOUNDATION_TITLE_PILE"]));
            }
            set {
                this["FOUNDATION_TITLE_PILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fondation : Semelles isolées et filantes")]
        public string FOUNDATION_TITLE_FOOTING {
            get {
                return ((string)(this["FOUNDATION_TITLE_FOOTING"]));
            }
            set {
                this["FOUNDATION_TITLE_FOOTING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fondation : Radier")]
        public string FOUNDATION_TITLE_RAFT {
            get {
                return ((string)(this["FOUNDATION_TITLE_RAFT"]));
            }
            set {
                this["FOUNDATION_TITLE_RAFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sans titre")]
        public string TYPE_NAME_VIEWPORT_WITHOUT_TITLE {
            get {
                return ((string)(this["TYPE_NAME_VIEWPORT_WITHOUT_TITLE"]));
            }
            set {
                this["TYPE_NAME_VIEWPORT_WITHOUT_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DCE Structure 3D")]
        public string TEMPLATE_NAME_THREED_VIEW {
            get {
                return ((string)(this["TEMPLATE_NAME_THREED_VIEW"]));
            }
            set {
                this["TEMPLATE_NAME_THREED_VIEW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DCE Structure Etage Courant")]
        public string TEMPLATE_NAME_STANDARD_FLOOR {
            get {
                return ((string)(this["TEMPLATE_NAME_STANDARD_FLOOR"]));
            }
            set {
                this["TEMPLATE_NAME_STANDARD_FLOOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DCE Structure Fondation")]
        public string TEMPLATE_NAME_FOUNDATION {
            get {
                return ((string)(this["TEMPLATE_NAME_FOUNDATION"]));
            }
            set {
                this["TEMPLATE_NAME_FOUNDATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hauteur")]
        public string PARA_NAME_DIM_HEIGHT {
            get {
                return ((string)(this["PARA_NAME_DIM_HEIGHT"]));
            }
            set {
                this["PARA_NAME_DIM_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Largeur")]
        public string PARA_NAME_DIM_WIDTH {
            get {
                return ((string)(this["PARA_NAME_DIM_WIDTH"]));
            }
            set {
                this["PARA_NAME_DIM_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poutre type")]
        public string PARA_NAME_BEAM_TYPE {
            get {
                return ((string)(this["PARA_NAME_BEAM_TYPE"]));
            }
            set {
                this["PARA_NAME_BEAM_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fondation")]
        public string KEYWORD_FOUNDATION {
            get {
                return ((string)(this["KEYWORD_FOUNDATION"]));
            }
            set {
                this["KEYWORD_FOUNDATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FON-PIEUX")]
        public string FAMILY_NAME_PILE {
            get {
                return ((string)(this["FAMILY_NAME_PILE"]));
            }
            set {
                this["FAMILY_NAME_PILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Charge-Point 2.5mm")]
        public string TYPE_NAME_POINT_LOAD {
            get {
                return ((string)(this["TYPE_NAME_POINT_LOAD"]));
            }
            set {
                this["TYPE_NAME_POINT_LOAD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Titre en haut")]
        public string PARA_NAME_SHEET_TITLE {
            get {
                return ((string)(this["PARA_NAME_SHEET_TITLE"]));
            }
            set {
                this["PARA_NAME_SHEET_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REI")]
        public string PARA_NAME_SHEET_REI {
            get {
                return ((string)(this["PARA_NAME_SHEET_REI"]));
            }
            set {
                this["PARA_NAME_SHEET_REI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sans sujet")]
        public string PARA_VALUE_SHEET_REI_NA {
            get {
                return ((string)(this["PARA_VALUE_SHEET_REI_NA"]));
            }
            set {
                this["PARA_VALUE_SHEET_REI_NA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POU-BA")]
        public string FAMILY_NAME_BEAM {
            get {
                return ((string)(this["FAMILY_NAME_BEAM"]));
            }
            set {
                this["FAMILY_NAME_BEAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".rfa")]
        public string RVT_FAMILY_EXTENSION {
            get {
                return ((string)(this["RVT_FAMILY_EXTENSION"]));
            }
            set {
                this["RVT_FAMILY_EXTENSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.355")]
        public double LEGEND_POSITION_X_MAX {
            get {
                return ((double)(this["LEGEND_POSITION_X_MAX"]));
            }
            set {
                this["LEGEND_POSITION_X_MAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.033")]
        public double LEGEND_POSITION_X_MIN {
            get {
                return ((double)(this["LEGEND_POSITION_X_MIN"]));
            }
            set {
                this["LEGEND_POSITION_X_MIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.009")]
        public double LEGEND_POSITION_Y_MIN_L {
            get {
                return ((double)(this["LEGEND_POSITION_Y_MIN_L"]));
            }
            set {
                this["LEGEND_POSITION_Y_MIN_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.056")]
        public double LEGEND_POSITION_Y_MIN_R {
            get {
                return ((double)(this["LEGEND_POSITION_Y_MIN_R"]));
            }
            set {
                this["LEGEND_POSITION_Y_MIN_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double LEGEND_POSITION_Y_MAX_L {
            get {
                return ((double)(this["LEGEND_POSITION_Y_MAX_L"]));
            }
            set {
                this["LEGEND_POSITION_Y_MAX_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.858")]
        public double LEGEND_POSITION_Y_MAX_R {
            get {
                return ((double)(this["LEGEND_POSITION_Y_MAX_R"]));
            }
            set {
                this["LEGEND_POSITION_Y_MAX_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ossature")]
        public string CATEGORY_NAME_BEAM {
            get {
                return ((string)(this["CATEGORY_NAME_BEAM"]));
            }
            set {
                this["CATEGORY_NAME_BEAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bas")]
        public string KEYWORD_BOTTOM_LEVEL {
            get {
                return ((string)(this["KEYWORD_BOTTOM_LEVEL"]));
            }
            set {
                this["KEYWORD_BOTTOM_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BN")]
        public string BEAM_TYPE_SIGN_BN {
            get {
                return ((string)(this["BEAM_TYPE_SIGN_BN"]));
            }
            set {
                this["BEAM_TYPE_SIGN_BN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Talon PV")]
        public string BEAM_TYPE_SIGN_TAL {
            get {
                return ((string)(this["BEAM_TYPE_SIGN_TAL"]));
            }
            set {
                this["BEAM_TYPE_SIGN_TAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PR")]
        public string BEAM_TYPE_SIGN_POUR {
            get {
                return ((string)(this["BEAM_TYPE_SIGN_POUR"]));
            }
            set {
                this["BEAM_TYPE_SIGN_POUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LT")]
        public string BEAM_TYPE_SIGN_LINT {
            get {
                return ((string)(this["BEAM_TYPE_SIGN_LINT"]));
            }
            set {
                this["BEAM_TYPE_SIGN_LINT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BEAM_TYPE_SIGN_POU {
            get {
                return ((string)(this["BEAM_TYPE_SIGN_POU"]));
            }
            set {
                this["BEAM_TYPE_SIGN_POU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BN")]
        public string BEAM_TYPE_SYNT_BN {
            get {
                return ((string)(this["BEAM_TYPE_SYNT_BN"]));
            }
            set {
                this["BEAM_TYPE_SYNT_BN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TAL")]
        public string BEAM_TYPE_SYNT_TAL {
            get {
                return ((string)(this["BEAM_TYPE_SYNT_TAL"]));
            }
            set {
                this["BEAM_TYPE_SYNT_TAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POUR")]
        public string BEAM_TYPE_SYNT_POUR {
            get {
                return ((string)(this["BEAM_TYPE_SYNT_POUR"]));
            }
            set {
                this["BEAM_TYPE_SYNT_POUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LINT")]
        public string BEAM_TYPE_SYNT_LINT {
            get {
                return ((string)(this["BEAM_TYPE_SYNT_LINT"]));
            }
            set {
                this["BEAM_TYPE_SYNT_LINT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POU")]
        public string BEAM_TYPE_SYNT_POU {
            get {
                return ((string)(this["BEAM_TYPE_SYNT_POU"]));
            }
            set {
                this["BEAM_TYPE_SYNT_POU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LON")]
        public string BEAM_TYPE_SYNT_LON {
            get {
                return ((string)(this["BEAM_TYPE_SYNT_LON"]));
            }
            set {
                this["BEAM_TYPE_SYNT_LON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string BEAM_TYPE_SIGN_LON {
            get {
                return ((string)(this["BEAM_TYPE_SIGN_LON"]));
            }
            set {
                this["BEAM_TYPE_SIGN_LON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double CHECK_BN_MAX_HEIGHT_METER {
            get {
                return ((double)(this["CHECK_BN_MAX_HEIGHT_METER"]));
            }
            set {
                this["CHECK_BN_MAX_HEIGHT_METER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.18")]
        public double CHECK_PV_MAX_WIDTH_METER {
            get {
                return ((double)(this["CHECK_PV_MAX_WIDTH_METER"]));
            }
            set {
                this["CHECK_PV_MAX_WIDTH_METER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sols")]
        public string CATEGORY_NAME_FLOOR {
            get {
                return ((string)(this["CATEGORY_NAME_FLOOR"]));
            }
            set {
                this["CATEGORY_NAME_FLOOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FONDATIONS")]
        public string LEVEL_NAME_FOUDATION {
            get {
                return ((string)(this["LEVEL_NAME_FOUDATION"]));
            }
            set {
                this["LEVEL_NAME_FOUDATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bas RDC")]
        public string LEVEL_NAME_BOTTOM_L1 {
            get {
                return ((string)(this["LEVEL_NAME_BOTTOM_L1"]));
            }
            set {
                this["LEVEL_NAME_BOTTOM_L1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PH RDC")]
        public string LEVEL_NAME_TOP_L1 {
            get {
                return ((string)(this["LEVEL_NAME_TOP_L1"]));
            }
            set {
                this["LEVEL_NAME_TOP_L1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.27")]
        public double TITLEBLOCK_WIDTH {
            get {
                return ((double)(this["TITLEBLOCK_WIDTH"]));
            }
            set {
                this["TITLEBLOCK_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double TITLEBLOCK_LENGTH {
            get {
                return ((double)(this["TITLEBLOCK_LENGTH"]));
            }
            set {
                this["TITLEBLOCK_LENGTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Matériau structurel")]
        public string PARA_NAME_STR_MATERIAL {
            get {
                return ((string)(this["PARA_NAME_STR_MATERIAL"]));
            }
            set {
                this["PARA_NAME_STR_MATERIAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Béton - Coulé sur place - Béton25")]
        public string MAT_NAME_BA25 {
            get {
                return ((string)(this["MAT_NAME_BA25"]));
            }
            set {
                this["MAT_NAME_BA25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Béton - Coulé sur place - Béton30")]
        public string MAT_NAME_BA30 {
            get {
                return ((string)(this["MAT_NAME_BA30"]));
            }
            set {
                this["MAT_NAME_BA30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Béton - Coulé sur place - Béton35")]
        public string MAT_NAME_BA35 {
            get {
                return ((string)(this["MAT_NAME_BA35"]));
            }
            set {
                this["MAT_NAME_BA35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Béton - Coulé sur place - Béton40")]
        public string MAT_NAME_BA40 {
            get {
                return ((string)(this["MAT_NAME_BA40"]));
            }
            set {
                this["MAT_NAME_BA40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Béton - Coulé sur place - Béton45")]
        public string MAT_NAME_BA45 {
            get {
                return ((string)(this["MAT_NAME_BA45"]));
            }
            set {
                this["MAT_NAME_BA45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BA25")]
        public string MAT_SYNTAXE_BA25 {
            get {
                return ((string)(this["MAT_SYNTAXE_BA25"]));
            }
            set {
                this["MAT_SYNTAXE_BA25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BA30")]
        public string MAT_SYNTAXE_BA30 {
            get {
                return ((string)(this["MAT_SYNTAXE_BA30"]));
            }
            set {
                this["MAT_SYNTAXE_BA30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BA35")]
        public string MAT_SYNTAXE_BA35 {
            get {
                return ((string)(this["MAT_SYNTAXE_BA35"]));
            }
            set {
                this["MAT_SYNTAXE_BA35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BA40")]
        public string MAT_SYNTAXE_BA40 {
            get {
                return ((string)(this["MAT_SYNTAXE_BA40"]));
            }
            set {
                this["MAT_SYNTAXE_BA40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BA45")]
        public string MAT_SYNTAXE_BA45 {
            get {
                return ((string)(this["MAT_SYNTAXE_BA45"]));
            }
            set {
                this["MAT_SYNTAXE_BA45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUTRE")]
        public string MAT_SYNTAXE_OTHER {
            get {
                return ((string)(this["MAT_SYNTAXE_OTHER"]));
            }
            set {
                this["MAT_SYNTAXE_OTHER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pieux")]
        public string KEYWOARD_FOUNDATION_TYPE_PILE {
            get {
                return ((string)(this["KEYWOARD_FOUNDATION_TYPE_PILE"]));
            }
            set {
                this["KEYWOARD_FOUNDATION_TYPE_PILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Semelles")]
        public string KEYWOARD_FOUNDATION_TYPE_FOOTING {
            get {
                return ((string)(this["KEYWOARD_FOUNDATION_TYPE_FOOTING"]));
            }
            set {
                this["KEYWOARD_FOUNDATION_TYPE_FOOTING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Radier")]
        public string KEYWOARD_FOUNDATION_TYPE_RAFT {
            get {
                return ((string)(this["KEYWOARD_FOUNDATION_TYPE_RAFT"]));
            }
            set {
                this["KEYWOARD_FOUNDATION_TYPE_RAFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Puits")]
        public string KEYWOARD_FOUNDATION_TYPE_DEEP_FOOTING {
            get {
                return ((string)(this["KEYWOARD_FOUNDATION_TYPE_DEEP_FOOTING"]));
            }
            set {
                this["KEYWOARD_FOUNDATION_TYPE_DEEP_FOOTING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fondation : Puits")]
        public string FOUNDATION_TITLE_DEEP_FOOTING {
            get {
                return ((string)(this["FOUNDATION_TITLE_DEEP_FOOTING"]));
            }
            set {
                this["FOUNDATION_TITLE_DEEP_FOOTING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vues")]
        public string CATEGORY_NAME_VIEW {
            get {
                return ((string)(this["CATEGORY_NAME_VIEW"]));
            }
            set {
                this["CATEGORY_NAME_VIEW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vue en plan")]
        public string FAMILY_TYPE_NAME_STR_PLAN {
            get {
                return ((string)(this["FAMILY_TYPE_NAME_STR_PLAN"]));
            }
            set {
                this["FAMILY_TYPE_NAME_STR_PLAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Niveaux")]
        public string CATEGORY_NAME_LEVEL {
            get {
                return ((string)(this["CATEGORY_NAME_LEVEL"]));
            }
            set {
                this["CATEGORY_NAME_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cartouche")]
        public string KEYWORD_TITLEBLOCK {
            get {
                return ((string)(this["KEYWORD_TITLEBLOCK"]));
            }
            set {
                this["KEYWORD_TITLEBLOCK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POT-BA-RECT")]
        public string FAMILY_NAME_RECT_COLUMN {
            get {
                return ((string)(this["FAMILY_NAME_RECT_COLUMN"]));
            }
            set {
                this["FAMILY_NAME_RECT_COLUMN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POT-BA-ROND")]
        public string FAMILY_NAME_ROND_COLUMN {
            get {
                return ((string)(this["FAMILY_NAME_ROND_COLUMN"]));
            }
            set {
                this["FAMILY_NAME_ROND_COLUMN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POT")]
        public string COLUMN_SYNT {
            get {
                return ((string)(this["COLUMN_SYNT"]));
            }
            set {
                this["COLUMN_SYNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Diamètre")]
        public string PARA_NAME_DIM_DIAMETER {
            get {
                return ((string)(this["PARA_NAME_DIM_DIAMETER"]));
            }
            set {
                this["PARA_NAME_DIM_DIAMETER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string KEYWORD_ROND_COLUMN_DIM {
            get {
                return ((string)(this["KEYWORD_ROND_COLUMN_DIM"]));
            }
            set {
                this["KEYWORD_ROND_COLUMN_DIM"] = value;
            }
        }
    }
}
