//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEStudyTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DCE A3 Standard")]
        public string TITLEBLOCK_NAME {
            get {
                return ((string)(this["TITLEBLOCK_NAME"]));
            }
            set {
                this["TITLEBLOCK_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Légendes")]
        public string STANDARD_LEGEND_NAME {
            get {
                return ((string)(this["STANDARD_LEGEND_NAME"]));
            }
            set {
                this["STANDARD_LEGEND_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Charge Verticale par Pieux en Tonnes à ELS(G+Q) Test")]
        public string PILE_FOUNDATION_TITLE {
            get {
                return ((string)(this["PILE_FOUNDATION_TITLE"]));
            }
            set {
                this["PILE_FOUNDATION_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fondation : Semelles isolées et Filantes")]
        public string FOOTING_FOUNDATION_TITLE {
            get {
                return ((string)(this["FOOTING_FOUNDATION_TITLE"]));
            }
            set {
                this["FOOTING_FOUNDATION_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fondation : Radier")]
        public string GROUND_SLAB_FOUNDATION_TITLE {
            get {
                return ((string)(this["GROUND_SLAB_FOUNDATION_TITLE"]));
            }
            set {
                this["GROUND_SLAB_FOUNDATION_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sans titre")]
        public string VIEWPORT_WITHOUT_TITLE_TYPE_NAME {
            get {
                return ((string)(this["VIEWPORT_WITHOUT_TITLE_TYPE_NAME"]));
            }
            set {
                this["VIEWPORT_WITHOUT_TITLE_TYPE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DCE Structure 3D")]
        public string THREED_VIEW_TEMPLATE_NAME {
            get {
                return ((string)(this["THREED_VIEW_TEMPLATE_NAME"]));
            }
            set {
                this["THREED_VIEW_TEMPLATE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DCE Structure Etage Courant")]
        public string STANDARD_FLOOR_TEMPLATE_NAME {
            get {
                return ((string)(this["STANDARD_FLOOR_TEMPLATE_NAME"]));
            }
            set {
                this["STANDARD_FLOOR_TEMPLATE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DCE Structure Fondation")]
        public string FOUNDATION_TEMPLATE_NAME {
            get {
                return ((string)(this["FOUNDATION_TEMPLATE_NAME"]));
            }
            set {
                this["FOUNDATION_TEMPLATE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hauteur")]
        public string BEAM_HEIGHT_PARAMETER {
            get {
                return ((string)(this["BEAM_HEIGHT_PARAMETER"]));
            }
            set {
                this["BEAM_HEIGHT_PARAMETER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Largeur")]
        public string BEAM_WIDTH_PARAMETER {
            get {
                return ((string)(this["BEAM_WIDTH_PARAMETER"]));
            }
            set {
                this["BEAM_WIDTH_PARAMETER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poutre type")]
        public string BEAM_TYPE_PARAMETER {
            get {
                return ((string)(this["BEAM_TYPE_PARAMETER"]));
            }
            set {
                this["BEAM_TYPE_PARAMETER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fondation")]
        public string FOUNDATION_KEY_WORD {
            get {
                return ((string)(this["FOUNDATION_KEY_WORD"]));
            }
            set {
                this["FOUNDATION_KEY_WORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FON-PIEUX")]
        public string PILE_TYPE_NAME {
            get {
                return ((string)(this["PILE_TYPE_NAME"]));
            }
            set {
                this["PILE_TYPE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Charge-Point 2.5mm")]
        public string POINT_LOAD_TYPE_NAME {
            get {
                return ((string)(this["POINT_LOAD_TYPE_NAME"]));
            }
            set {
                this["POINT_LOAD_TYPE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Titre en haut")]
        public string SHEET_TITLE_PARA_NAME {
            get {
                return ((string)(this["SHEET_TITLE_PARA_NAME"]));
            }
            set {
                this["SHEET_TITLE_PARA_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REI")]
        public string SHEET_REI_PARA_NAME {
            get {
                return ((string)(this["SHEET_REI_PARA_NAME"]));
            }
            set {
                this["SHEET_REI_PARA_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sans sujet")]
        public string SHEET_REI_NA_VALUE {
            get {
                return ((string)(this["SHEET_REI_NA_VALUE"]));
            }
            set {
                this["SHEET_REI_NA_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POU-BA")]
        public string BEAM_FAMILY_NAME {
            get {
                return ((string)(this["BEAM_FAMILY_NAME"]));
            }
            set {
                this["BEAM_FAMILY_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".rfa")]
        public string RVT_FAMILY_EXTENSION {
            get {
                return ((string)(this["RVT_FAMILY_EXTENSION"]));
            }
            set {
                this["RVT_FAMILY_EXTENSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.355")]
        public double LEGEND_POSITION_X_MAX {
            get {
                return ((double)(this["LEGEND_POSITION_X_MAX"]));
            }
            set {
                this["LEGEND_POSITION_X_MAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.033")]
        public double LEGEND_POSITION_X_MIN {
            get {
                return ((double)(this["LEGEND_POSITION_X_MIN"]));
            }
            set {
                this["LEGEND_POSITION_X_MIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.009")]
        public double LEGEND_POSITION_Y_MIN_L {
            get {
                return ((double)(this["LEGEND_POSITION_Y_MIN_L"]));
            }
            set {
                this["LEGEND_POSITION_Y_MIN_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.056")]
        public double LEGEND_POSITION_Y_MIN_R {
            get {
                return ((double)(this["LEGEND_POSITION_Y_MIN_R"]));
            }
            set {
                this["LEGEND_POSITION_Y_MIN_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double LEGEND_POSITION_Y_MAX_L {
            get {
                return ((double)(this["LEGEND_POSITION_Y_MAX_L"]));
            }
            set {
                this["LEGEND_POSITION_Y_MAX_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.858")]
        public double LEGEND_POSITION_Y_MAX_R {
            get {
                return ((double)(this["LEGEND_POSITION_Y_MAX_R"]));
            }
            set {
                this["LEGEND_POSITION_Y_MAX_R"] = value;
            }
        }
    }
}
